<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 (Total recall)

| Term       | Brief description |
|------------|-------------------|
| Subsetting |Selecting a subset of a list/array|
| Indexing   |Selecting 1 element of a list/array|
| Slicing    |Selecting a range of elements of a list/array|
| Masking    |Selecting elements based on True/False|

# Exercise 2 (Show me the ‘odd’ letters)

In [ ]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
print(np_array_2d)
first = np_array_2d[::,0]
print(first)
first_int = first.astype(int)
print(first_int)


[['1' 'A']
 ['3' 'C']
 ['2' 'B']
 ['4' 'D']
 ['5' 'E']
 ['7' 'G']
 ['6' 'F']
 ['8' 'H']
 ['10' 'J']
 ['9' 'I']]
['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']


TypeError: Cannot construct a dtype from an array

# Exercise 3

In [30]:
arr = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])
arr[arr < 50] = -1
arr[arr > 50] = 1
arr[arr == 50] = 0
print(arr)




[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
